# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go vet ./...
  - go test -coverprofile c.out ./...

builds:
- env:
  - CGO_ENABLED=0 # this is needed otherwise the Docker image build is faulty
  goarch:
  - amd64
  goos:
  - linux

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

signs:
- artifacts: checksum
  args: ["-u", "E57761BCB035C49A7068EF97083880A377733DD7", "--output", "${signature}", "--detach-sign", "${artifact}"]

dockers:
- image_templates:
  - "docker.io/braindoctor/znapzend-exporter:v{{ .Version }}"
  - "docker.io/braindoctor/znapzend-exporter:v{{ .Major }}"

nfpms:
- vendor: ccremer
  homepage: https://github.com/ccremer/znapzend-exporter
  maintainer: ccremer
  description: A prometheus exporter reporting on the status of Znapzend ZFS backups
  license: GPL 3.0
  file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  formats:
  - deb
  - rpm

changelog:
  sort: asc
  filters:
    exclude:
    - '^Docs:'
    - '^Test:'
    - '^Refactor:'
    - '^Merge pull request'

release:
  github:
    owner: ccremer
    name: znapzend-exporter
