ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Znapzend Exporter

ifdef::status[]
image:https://img.shields.io/github/workflow/status/ccremer/znapzend-exporter/Build/master[Build,link=https://github.com/ccremer/znapzend-exporter/actions?query=workflow%3ABuild]
image:https://img.shields.io/codeclimate/maintainability/ccremer/znapzend-exporter[Maintainability,link=https://codeclimate.com/github/ccremer/znapzend-exporter]
image:https://img.shields.io/codeclimate/coverage/ccremer/znapzend-exporter[Tests,link=https://codeclimate.com/github/ccremer/znapzend-exporter]
image:https://img.shields.io/github/v/release/ccremer/znapzend-exporter[Releases,link=https://github.com/ccremer/znapzend-exporter/releases]
image:https://img.shields.io/github/license/ccremer/znapzend-exporter[License,link=https://github.com/ccremer/znapzend-exporter/blob/master/LICENSE]
image:https://img.shields.io/docker/pulls/braindoctor/znapzend-exporter[Docker image,link=https://hub.docker.com/r/braindoctor/znapzend-exporter]
endif::[]

== About

This is a Prometheus exporter that works together with https://github.com/oetiker/znapzend[ZnapZend],
a ZFS snapshot and backup tool. It is written in Perl and lacks modern monitoring integration, so this
exporter tries to bridge the gap by providing a Prometheus scrape target.

Znapzend supports executing arbitrary commands before and after `zfs snapshot` and `zfs send`,
and this tool leverages this feature by providing a endpoint URLs for CURL requests.

== Installing

=== With Docker

. `docker run -d --name znapzend-exporter -p "8080:8080" braindoctor/znapzend-exporter`

=== Binary

. Download latest binary from the https://github.com/ccremer/znapzend-exporter/releases[Releases page]
. `chmod +x $the_binary`
. `mv $the_binary /usr/local/bin/znapzend-exporter`
. `znapzend-exporter --help`

== Configuration

`znapzend-exporter` can be configured with CLI flags.

[source,console]
----
znapzend-exporter (version v0.0.0-snapshot, <commit>, <date>)

All flags can be read from Environment variables as well (replace . with _ , e.g. LOG_LEVEL).
However, CLI flags take precedence.

      --bindAddr string    IP Address to bind to listen for Prometheus scrapes (default ":8080")
      --log.level string   Logging level (default "info")
pflag: help requested
----

TIP: All flags are also configurable with Environment variables. Replace the `.` char with `_` and
     uppercase the names in order for them to be recognized, e.g. `--log.level debug` becomes
     `LOG_LEVEL=debug`

== Developing

=== Requirements

* Go
* https://github.com/goreleaser/goreleaser[Goreleaser]

=== Building

. `goreleaser release --snapshot --rm-dist`

=== Unit Test

. `go test ./...`
