---
name: Build

on:
  push:
    branches:
    - "*"
    tags-ignore:
    - "*"
  pull_request:
    types: [opened, reopened]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.13.8'
    - uses: actions/cache@v1
      with:
        path: /home/runner/go/pkg/mod
        key: go-mod-build
    - uses: goreleaser/goreleaser-action@v1
      with:
        args: release --snapshot --skip-sign
    - name: Test & Publish Code Coverage
      uses: paambaati/codeclimate-action@v2.5.6
      env:
        CC_TEST_REPORTER_ID: e83a1c47936e887bb37d1e37ebd3395744d4b73693a3c6e199294182be045210
      with:
        coverageCommand: go test -coverprofile c.out ./...
        prefix: znapzend-exporter
        coverageLocations: ""
