---
name: Release

on:
  push:
    tags:
    - "*"

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: /home/runner/go/pkg/mod
        key: go-mod
    - name: Run unit tests
      run: go test ./...
  goreleaser:
    runs-on: ubuntu-latest
    needs:
    - unit
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: /home/runner/go/pkg/mod
        key: go-mod
    - name: Login to Docker hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - uses: goreleaser/goreleaser-action@v1
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
